### ISSUE TITLE
Using wrong way of conditonal check in javascript

### ISSUE THREAD

**Issue by pulsarinside** [satheevan/codepractices#1]
https://github.com/satheevan/codepractices/blob/8ad676d90d26b7816716cc3558e4188e933f7857/zero.js#L3

In javascript when checking for condition should not use == you can use === 
if (num == 0) should be replaced with if (num === 0)

Also remember this is javascript we can just use num itself for conditional check.

if (!num) 

In javascript and clanguage 
0 is false, and 1 is true

Since the num is 0 we can easily check with if (!num)

**Comment by satheevan** [comment]
Okay brother I will correct it.
